apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rustinelibre.fullname" . }}
  labels:
    {{- include "rustinelibre.labels" . | nindent 4 }}
data:
  mailer-sender: {{ .Values.mailer.sender | quote }}
  php-host: {{ .Values.php.host | quote }}
  php-app-env: {{ .Values.php.appEnv | quote }}
  php-app-debug: {{ .Values.php.appDebug | quote }}
  php-cors-allow-origin: {{ .Values.php.corsAllowOrigin | quote }}
  php-trusted-hosts: {{ .Values.php.trustedHosts | quote }}
  php-trusted-proxies: "{{ join "," .Values.php.trustedProxies }}"
  mercure-url: "http://{{ include "rustinelibre.fullname" . }}/.well-known/mercure"
  mercure-public-url: {{ .Values.mercure.publicUrl | default "http://127.0.0.1/.well-known/mercure" | quote }}
  mercure-extra-directives: {{ .Values.mercure.extraDirectives | quote }}
  php-storage-bucket: {{ .Values.php.storage.bucket | quote }}
  php-storage-endpoint: {{ .Values.php.storage.endpoint | quote }}
  php-storage-region: {{ .Values.php.storage.region | quote }}
  php-storage-use-path-style-endpoint: {{ .Values.php.storage.usePathStyleEndpoint | quote }}
  google-oauth-redirection-uri: {{ .Values.php.google-oauth.redirect_uri | quote }}
  google-oauth-javascript-origins: {{ .Values.php.google-oauth.javascript_origins | quote }}
  google-oauth-cert-path: {{ .Values.php.google-oauth.cert_path | quote }}
  google-oauth-token-uri: {{ .Values.php.google-oauth.token_uri | quote }}
  google-oauth-auth-uri: {{ .Values.php.google-oauth.auth_uri | quote }}
