parameters:
    storage_endpoint: '%env(string:STORAGE_ENDPOINT)%'
    storage_region: '%env(string:STORAGE_REGION)%'
    storage_use_path_style_endpoint: '%env(bool:STORAGE_USE_PATH_STYLE_ENDPOINT)%'
    storage_key: '%env(string:STORAGE_KEY)%'
    storage_secret: '%env(string:STORAGE_SECRET)%'
    google_client_id: '%env(string:GOOGLE_CLIENT_ID)%'
    google_project_id: '%env(string:GOOGLE_PROJECT_ID)%'
    google_client_secret: '%env(string:GOOGLE_CLIENT_SECRET)%'
    google_auth_uri: '%env(string:GOOGLE_AUTH_URI)%'
    google_token_uri: '%env(string:GOOGLE_TOKEN_URI)%'
    google_auth_provider_cert_url: '%env(string:GOOGLE_AUTH_PROVIDER_CERT_URL)%'
    google_redirect_uris: '%env(string:GOOGLE_REDIRECT_URIS)%'
    google_javascript_origins: '%env(string:GOOGLE_JAVASCRIPT_ORIGINS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $mailerSender: "%env(MAILER_SENDER)%"
            string $webAppUrl: "%env(WEB_APP_URL)%"
            string $projectDir: "%kernel.project_dir%"
            string $firebaseProjectId: "%env(FIREBASE_PROJECT_ID)%"
            string $firebasePrivateKey: "%env(FIREBASE_PRIVATE_KEY)%"
            string $firebasePrivateKeyId: "%env(FIREBASE_PRIVATE_KEY_ID)%"
            string $firebaseClientEmail: "%env(FIREBASE_CLIENT_EMAIL)%"
            string $firebaseClientId: "%env(FIREBASE_CLIENT_ID)%"
            string $firebaseAuthUri: "%env(FIREBASE_AUTH_URI)%"
            string $firebaseTokenUri: "%env(FIREBASE_TOKEN_URI)%"
            string $firebaseAuthProvider: "%env(FIREBASE_AUTH_PROVIDER)%"
            string $firebaseClientCertUrl: "%env(FIREBASE_CLIENT_CERT_URL)%"
            string $firebaseUniverseDomain: "%env(FIREBASE_UNIVERSE_DOMAIN)%"
            string $storageBucket: "%env(STORAGE_BUCKET)%"
            string $googleClientId: "%env(GOOGLE_CLIENT_ID)%"
            string $googleProjectId: "%env(GOOGLE_PROJECT_ID)%"
            string $googleClientSecret: "%env(GOOGLE_CLIENT_SECRET)%"
            string $googleAuthUri: "%env(GOOGLE_AUTH_URI)%"
            string $googleTokenUri: "%env(GOOGLE_TOKEN_URI)%"
            string $googleAuthProviderCertUrl: "%env(GOOGLE_AUTH_PROVIDER_CERT_URL)%"
            string $googleRedirectUris: "%env(GOOGLE_REDIRECT_URIS)%"
            string $googleJavascriptOrigins: "%env(GOOGLE_JAVASCRIPT_ORIGINS)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@App\OpenApi\OpenApiFactory.inner' ]
        autoconfigure: false

    App\Resources\Services\Faker\DateTimeImmutableProvider: ~

    App\Resources\Services\Faker\AutoDiagnosticPrestationProvider: ~

    Aws\S3\S3Client:
        arguments:
            -   endpoint: '%storage_endpoint%'
                version: 'latest'
                region: '%storage_region%'
                use_path_style_endpoint: '%storage_use_path_style_endpoint%'
                credentials:
                    key: '%storage_key%'
                    secret: '%storage_secret%'
